import type { Metadata } from "next"
import "./styles/reset.css"
import "./styles/globals.css"

import StyledComponentsRegistry from "./lib/registry"
import { jost } from "./lib/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={jost.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
